services:
  api:
    container_name: api
    image: golang:1.19-alpine
    build: ./api
    volumes:
      - ./api:/app
    working_dir: /app
    command: ["go", "run", "main.go"]
    ports:
      - "8080:8080"
